name: Deploy to Deno
on:
  push:
    branches: master
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: kiwano
          entrypoint: https://deno.land/std/http/file_server.ts
          root: ./static_web
